### PR TITLE
Fix crash updating a UIImage extension file

### LINKED ISSUE #91: Crash updating a UIImage extension file
We get a crash when trying to download new assets.

I found a line that crashes. It's in `XcodeImagesExporterBase.swift`, line 65:
```
private func appendContent(string: String, to fileURL: URL) throws -> String {
    var existingContents = try String(contentsOf: URL(fileURLWithPath: fileURL.path), encoding: .utf8)

    if let index = existingContents.lastIndex(of: "}") {
       let nextIndex = existingContents.index(after: index)
       existingContents.replaceSubrange(index...nextIndex, with: string)
    }
    return existingContents
}
```

You assume that there will always be a character (newline) after the last brace, but for some reason, we don't have this newline in the generated file (we haven't edited this file).

So, I'm going to fix this by removing the last newline everywhere and changing the function above to:
```
private func appendContent(string: String, to fileURL: URL) throws -> String {
    var existingContents = try String(contentsOf: URL(fileURLWithPath: fileURL.path), encoding: .utf8)

    if let index = existingContents.lastIndex(of: "}") {
       existingContents.replaceSubrange(index... index, with: string)
    }
    return existingContents
}
```

### PR DESCRIPTION
**Pull request by NoFearJoe**
Closes #91

### CODE REVIEW

File: Tests/XcodeExportTests/XcodeIconsExporterTests.swift [hunk 1]
```diff
@@ -227,4 +228,67 @@ final class XcodeIconsExporterTests: XCTestCase {
...
+private extension XcodeIconsExporterTests {
+
+    func write(file: FileContents) throws {
+        let content = try XCTUnwrap(file.data)
+
+        let directoryURL = URL(fileURLWithPath: file.destination.directory.path)
+        try FileManager.default.createDirectory(atPath: directoryURL.path, withIntermediateDirectories: true, attributes: [:])
+        let fileURL = URL(fileURLWithPath: file.destination.url.path)
+
+        try content.write(to: fileURL, options: .atomicWrite)
```
Comment (subdan) [inline Tests/XcodeExportTests/XcodeIconsExporterTests.swift:291]: `UIImage+extension.swift` will be written to 

`/Users/USER_NAME/Library/Developer/Xcode/DerivedData/figma-export/Build/Products/Debug/~/UIImage+extension.swift`

Use [temporaryDirectory](https://developer.apple.com/documentation/foundation/filemanager/1642996-temporarydirectory) or store file in memory.

**Review by subdan — CHANGES_REQUESTED** [review]
Do not write files to DerivedData directory. Use system temporary directory.

**Review by subdan — APPROVED** [review]
